version: "3.9"

services: 
  back-end:
    build: .
    ports: 
     - 8888:3000

  mongodb:
    image: mongo:4.4
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports: 
     - 7777:27017
    volumes: 
     - data:/data/db
    container_name: bobsdb
volumes: 
  data: