version: "3.9"

services:

  traefik:
    image: traefik:2.4
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - "./traefik.toml:/traefik.toml"
      - "./traefik_dynamic.toml:/traefik_dynamic.toml"
    depends_on:
      - service
    networks:
      - internal
      - external
    container_name: traefik

  service:
    build: .
    networks:
      - internal
    deploy:
      mode: replicated
      replicas: 2
  
  mongodb:
    image: mongo:4.4
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports: 
     - 7777:27017
    volumes: 
     - data:/data/db
    container_name: bobsdb

volumes: 
  data:

networks:
  external:
  internal:
    internal: true
