[http.routers.dashboard]
rule = "PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
entrypoints = ["web"]
service = "api@internal"

[http.routers.myservice]
rule = "PathPrefix(`/`)"
entrypoints = ["web"]
service = "myservice"


[http.services.myservice.loadBalancer.healthCheck]
interval = "3s"
timeout = "1s"

[[http.services.myservice.loadBalancer.servers]]
url = "http://service:8080"